platform :ios, '12.0'
source 'https://cdn.cocoapods.org/'
flutter_application_path = '../'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
target 'Runner' do
  use_frameworks!
  use_modular_headers!
end